"""init_03_08

Revision ID: 12c9d64c423c
Revises:
Create Date: 2026-08-03 21:53:24.512956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import core.database  # noqa: F401 — для типа StrippedString

# revision identifiers, used by Alembic.
revision: str = '12c9d64c423c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', core.database.StrippedString(length=256), nullable=False, comment='Домен публикатора новости (напр. kompromat.ru). НЕ source — то, откуда пришёл контент'),
    sa.Column('reason', core.database.StrippedString(length=512), nullable=True, comment='Почему в списке: заказной / компрометирующий ресурс'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время добавления домена в чёрный список'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('domain = btrim(domain)', name='ck_black_domain_domain_trimmed'),
    sa.CheckConstraint('reason = btrim(reason)', name='ck_black_domain_reason_trimmed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', core.database.StrippedString(length=128), nullable=False, comment='Категория события (напр. надзорная санкция и юр.риск, PR-активность конкурента, репутационный риск)'),
    sa.Column('note', core.database.StrippedString(length=512), nullable=True, comment='Определение категории для аналитика: что под неё подпадает'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('name = btrim(name)', name='ck_category_name_trimmed'),
    sa.CheckConstraint('note = btrim(note)', name='ck_category_note_trimmed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', core.database.StrippedString(length=64), nullable=False, comment='Канал доставки: telegram, email, dashboard'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('name = btrim(name)', name='ck_channel_name_trimmed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', core.database.StrippedString(length=256), nullable=False, comment='Название компании (например, Бегемот, Рога и Копыта)'),
    sa.Column('inn', core.database.StrippedString(length=12), nullable=True, comment='ИНН конкурента (опционально, поиск по гос-реестрам)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('inn = btrim(inn)', name='ck_competitor_inn_trimmed'),
    sa.CheckConstraint('name = btrim(name)', name='ck_competitor_name_trimmed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn'),
    sa.UniqueConstraint('name')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', core.database.StrippedString(length=128), nullable=False, comment='Отдел: PR, Юристы, Аналитика, Маркетинг'),
    sa.Column('note', core.database.StrippedString(length=512), nullable=True, comment='Зона ответственности отдела: какие категории он ведёт'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('name = btrim(name)', name='ck_department_name_trimmed'),
    sa.CheckConstraint('note = btrim(note)', name='ck_department_note_trimmed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', core.database.StrippedString(length=256), nullable=False, comment='Название типа: судебный/надзорный риск, выигранный тендер, активный наём, расширение, M&A, закрытие объекта'),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False, comment='Слова-маркеры: [«прокуратура», «суд», «иск», «нарушения»]. По ним детектор матчит title события (вхождение подстроки)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('name = btrim(name)', name='ck_event_type_name_trimmed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_event_type_keywords', 'event_type', ['keywords'], unique=False, postgresql_using='gin')
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_display', core.database.StrippedString(length=128), nullable=False, comment='Каноническое имя для витрины и карты: «Волгоград». По нему группируем в дашборде'),
    sa.Column('name_aliases', postgresql.ARRAY(sa.String()), nullable=True, comment='Варианты написания в нижнем регистре: [«волгоград», «г. волгоград», «г волгоград»]'),
    sa.Column('macro_region', core.database.StrippedString(length=64), nullable=True, comment='Федеральный округ: ЦФО, ЮФО — для карты рынка'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Широта центра региона (WGS-84), для карты рынка'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Долгота центра региона (WGS-84), для карты рынка'),
    sa.CheckConstraint('macro_region = btrim(macro_region)', name='ck_region_macro_region_trimmed'),
    sa.CheckConstraint('name_display = btrim(name_display)', name='ck_region_name_display_trimmed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_display')
    )
    op.create_index('ix_region_name_aliases', 'region', ['name_aliases'], unique=False, postgresql_using='gin')
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', core.database.StrippedString(length=256), nullable=False, comment='Имя сайта/ресурса (например, hh.ru, авито, суд_реестр)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('name = btrim(name)', name='ck_source_name_trimmed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stop_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', core.database.StrippedString(length=512), nullable=False, comment='Слово или фраза для отсева (проверяется вхождением в title/text)'),
    sa.Column('type', sa.Enum('stop_word', 'stop_topic', 'false_positive', name='stop_type'), nullable=False, comment='stop_word — стоп-слово; stop_topic — стоп-тема; false_positive — ложное срабатывание'),
    sa.Column('note', core.database.StrippedString(length=512), nullable=True, comment='Пояснение для аналитика: почему добавили и от чего защищает'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('note = btrim(note)', name='ck_stop_word_note_trimmed'),
    sa.CheckConstraint('phrase = btrim(phrase)', name='ck_stop_word_phrase_trimmed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phrase', 'type', name='uq_stop_word_phrase_type')
    )
    op.create_table('topic_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('competitor', 'source', 'media', 'region', name='limit_scope'), nullable=False, comment='По какой группе считаем долю: competitor / source / media / region'),
    sa.Column('max_count', sa.Integer(), nullable=False, comment='Максимум событий на одну группу за окно; сверх — rejected(noise_limit)'),
    sa.Column('window', sa.Enum('run', 'day', 'week', name='limit_window'), server_default=sa.text("'week'"), nullable=False, comment='Окно подсчёта: run — один прогон, day — сутки, week — неделя'),
    sa.Column('note', core.database.StrippedString(length=512), nullable=True, comment='Напр.: «СКС занимает ~40% отчёта 5 недель подряд»'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('note = btrim(note)', name='ck_topic_limit_note_trimmed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', core.database.StrippedString(length=128), nullable=False, comment='Само поисковое слово/навык (например, Юрист, Python, Суд)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('keyword = btrim(keyword)', name='ck_trigger_keyword_trimmed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('search_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False, comment='Какого конкурента ищем'),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='На каком источнике ищем'),
    sa.Column('trigger_id', sa.Integer(), nullable=True, comment='По какому слову ищем (опционально, NULL = парсим источник в лоб)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'source_id', 'trigger_id', name='uq_search_task_config')
    )
    op.create_index('uq_search_task_no_trigger', 'search_task', ['competitor_id', 'source_id'], unique=True, postgresql_where=sa.text('trigger_id IS NULL'))
    op.create_table('source_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', core.database.StrippedString(length=256), nullable=False, comment='Найденный домен-кандидат. UNIQUE — не предлагать дважды'),
    sa.Column('competitor_id', sa.Integer(), nullable=True, comment='По какому конкуренту/запросу нашли'),
    sa.Column('evidence_url', core.database.StrippedString(length=512), nullable=True, comment='Ссылка-доказательство: где упомянут конкурент'),
    sa.Column('llm_assessment', sa.Text(), nullable=True, comment='Краткая оценка LLM: что за ресурс, релевантность, публичность'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='candidate_status'), server_default=sa.text("'pending'"), nullable=False, comment='pending → approved / rejected'),
    sa.Column('moderated_by', core.database.StrippedString(length=128), nullable=True, comment='Кто промодерировал'),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True, comment='Когда промодерировали'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда агент предложил'),
    sa.CheckConstraint('domain = btrim(domain)', name='ck_source_candidate_domain_trimmed'),
    sa.CheckConstraint('evidence_url = btrim(evidence_url)', name='ck_source_candidate_evidence_url_trimmed'),
    sa.CheckConstraint('moderated_by = btrim(moderated_by)', name='ck_source_candidate_moderated_by_trimmed'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', core.database.StrippedString(length=256), nullable=True, comment='ФИО — для читаемости в админке, не критично'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='В каком отделе числится (справочно, не для маршрутизации)'),
    sa.Column('email', core.database.StrippedString(length=256), nullable=False, comment='Адрес для канала email, он же логин API'),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True, comment='Числовой chat_id для канала telegram (sendMessage требует id, не @username). NULL, пока пользователь не привязал telegram'),
    sa.Column('password_hash', core.database.StrippedString(length=256), nullable=False, comment='bcrypt-хэш пароля для логина в API'),
    sa.Column('role', sa.Enum('pending', 'viewer', 'analyst', 'admin', name='user_role'), server_default=sa.text("'pending'"), nullable=False, comment='Уровень доступа к API (не отдел): pending/viewer/analyst/admin'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.CheckConstraint('email = btrim(email)', name='ck_user_email_trimmed'),
    sa.CheckConstraint('full_name = btrim(full_name)', name='ck_user_full_name_trimmed'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('raw_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_task_id', sa.Integer(), nullable=False, comment='Ссылка на задачу конфигурации. Через неё вытягиваем конкурента, источник и триггер'),
    sa.Column('status', sa.Enum('new', 'changed', 'error', name='raw_item_status'), server_default=sa.text("'new'"), nullable=False, comment='new/changed = новая строка; error = сбой сбора. При совпадении хэша строку не создаём, статус не трогаем'),
    sa.Column('content_hash', core.database.StrippedString(length=64), nullable=True, comment='Хэш от JSON контента для сверки через Redis. NULL при status=error'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Сырой извлечённый контент страницы в формате JSON. NULL при status=error'),
    sa.Column('html_file_path', core.database.StrippedString(length=512), nullable=True, comment='Путь к сохранённому слепку HTML на диске/S3 для истории. NULL при status=error'),
    sa.Column('source_request_url', core.database.StrippedString(length=512), nullable=True, comment='Ссылка на оригинальный веб-запрос парсера. NULL при ранней ошибке'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Текст ошибки при status=error. NULL для успешных'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время первой фиксации этого снимка в системе'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время последней СВЕРКИ. При совпадении хэша обновляем ТОЛЬКО это поле (статус не трогаем)'),
    sa.CheckConstraint('content_hash = btrim(content_hash)', name='ck_raw_item_content_hash_trimmed'),
    sa.CheckConstraint('html_file_path = btrim(html_file_path)', name='ck_raw_item_html_file_path_trimmed'),
    sa.CheckConstraint('source_request_url = btrim(source_request_url)', name='ck_raw_item_source_request_url_trimmed'),
    sa.ForeignKeyConstraint(['search_task_id'], ['search_task.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False, comment='Для какого типа значимого события'),
    sa.Column('priority', sa.Enum('p1', 'p2', 'p3', 'p4', name='priority_level'), nullable=False, comment='Для какого приоритета срабатывает правило'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Кому конкретно отправлять'),
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='В какой канал доставляем'),
    sa.Column('mode', sa.Enum('instant', 'digest', name='delivery_mode'), nullable=False, comment='instant (П1) | digest (П2)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type_id', 'priority', 'channel_id', 'user_id', name='uq_routing_rule_type_priority_channel_user')
    )
    op.create_table('normalized_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=False, comment='Ссылка назад на сырьё (drill-down, требование прозрачности ТЗ)'),
    sa.Column('competitor_id', sa.Integer(), nullable=True, comment='Конкурент. NULL если из текста однозначно не вытащили'),
    sa.Column('region_id', sa.Integer(), nullable=True, comment='Регион после lookup в region. NULL если не определён'),
    sa.Column('source_id', sa.Integer(), nullable=True, comment='Источник. Денормализовано из raw_item→search_task→source, чтобы не джойнить в два прыжка'),
    sa.Column('published_at', sa.Date(), nullable=True, comment='Дата события, нормализована к ISO из сырой строки (напр. «18 июля 2026»)'),
    sa.Column('title', core.database.StrippedString(length=512), nullable=False, comment='Заголовок события'),
    sa.Column('media_name', core.database.StrippedString(length=256), nullable=True, comment='СМИ-публикатор: «Big-news.ru, Москва». NULL для источников без публикатора (напр. hh.ru)'),
    sa.Column('media_domain', core.database.StrippedString(length=256), nullable=True, comment='Домен публикатора — для сверки с black_domain'),
    sa.Column('url', core.database.StrippedString(length=512), nullable=True, comment='Ссылка на конкретное событие (НЕ запрос парсера)'),
    sa.Column('text', sa.Text(), nullable=True, comment='Тело события. Вход для стоп-слов в BP-2 и для промпта LLM в BP-3'),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Источник-специфичные факты: {salary_from, salary_to, currency} для вакансий'),
    sa.Column('dedup_key', sa.String(length=64), nullable=False, comment='Хэш бизнес-полей (конкурент|заголовок|дата|регион). UNIQUE = дедуп через ON CONFLICT'),
    sa.Column('status', sa.Enum('ok', 'rejected', name='norm_status'), server_default=sa.text("'ok'"), nullable=False, comment='ok → идут в BP-3; rejected → помечены, не удаляем'),
    sa.Column('reject_reason', sa.Enum('black_domain', 'stop_word', 'stop_topic', 'false_positive', 'noise_limit', 'parse_error', name='reject_reason_t'), nullable=True, comment='Причина отсева. NULL для status=ok'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время нормализации события'),
    sa.CheckConstraint('media_domain = btrim(media_domain)', name='ck_normalized_item_media_domain_trimmed'),
    sa.CheckConstraint('media_name = btrim(media_name)', name='ck_normalized_item_media_name_trimmed'),
    sa.CheckConstraint('title = btrim(title)', name='ck_normalized_item_title_trimmed'),
    sa.CheckConstraint('url = btrim(url)', name='ck_normalized_item_url_trimmed'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_item.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_table('categorized_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_item_id', sa.Integer(), nullable=False, comment='1:1 ссылка на факты события. UNIQUE = одна разметка'),
    sa.Column('priority', sa.Enum('p1', 'p2', 'p3', 'p4', name='priority_level'), nullable=False, comment='Приоритет П1–П4 (от LLM)'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Категория события из справочника (LLM → lookup id)'),
    sa.Column('tonality', sa.Enum('positive', 'neutral', 'negative', 'alarming', 'irrelevant', name='tonality_level'), nullable=False, comment='Тональность (от LLM)'),
    sa.Column('media_index', sa.Numeric(precision=10, scale=2), nullable=True, comment='Медиаиндекс (охват/заметность) из лицензионного агрегатора. НЕ выход LLM. NULL если источника нет'),
    sa.Column('action', core.database.StrippedString(length=512), nullable=True, comment='Требуемое действие (черновик от LLM)'),
    sa.Column('deadline', sa.Date(), nullable=True, comment='Срок реакции. Считает код: П1 = дата+48ч, П2 = +7 дней'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='Ответственный отдел (LLM → lookup id)'),
    sa.Column('comment', core.database.StrippedString(length=512), nullable=True, comment='Комментарий от LLM'),
    sa.Column('llm_model', core.database.StrippedString(length=64), nullable=True, comment='Какая модель разметила (для аудита)'),
    sa.Column('prompt_version', core.database.StrippedString(length=32), nullable=True, comment='Версия промпта/правил (для перекатегоризации)'),
    sa.Column('categorized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда разметили (INSERT) или переразметили (UPDATE). По индексу BP-4 отбирает переразмеченные события (categorized_at > showcase_event.updated_at). onupdate срабатывает автоматически на ЛЮБОМ UPDATE через SQLAlchemy (и точечная правка атрибута, и bulk update()) — колонка не перечислена в .values(), компилятор сам подставит значение. НЕ сработает при INSERT ... ON CONFLICT DO UPDATE (это технически INSERT, не UPDATE) и при правке в обход SQLAlchemy — сырой SQL, DBeaver, pgAdmin: там колонку нужно проставлять руками'),
    sa.CheckConstraint('action = btrim(action)', name='ck_categorized_event_action_trimmed'),
    sa.CheckConstraint('comment = btrim(comment)', name='ck_categorized_event_comment_trimmed'),
    sa.CheckConstraint('llm_model = btrim(llm_model)', name='ck_categorized_event_llm_model_trimmed'),
    sa.CheckConstraint('prompt_version = btrim(prompt_version)', name='ck_categorized_event_prompt_version_trimmed'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['normalized_item_id'], ['normalized_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_item_id')
    )
    op.create_index(op.f('ix_categorized_event_categorized_at'), 'categorized_event', ['categorized_at'], unique=False)
    op.create_table('showcase_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categorized_event_id', sa.Integer(), nullable=False, comment='Ключ инкрементального UPSERT: одна строка витрины на размеченное событие'),
    sa.Column('raw_item_id', sa.Integer(), nullable=False, comment='Drill-down до сырья (из строки витрины → к исходнику)'),
    sa.Column('published_at', sa.Date(), nullable=True, comment='Дата события'),
    sa.Column('title', core.database.StrippedString(length=512), nullable=False, comment='Заголовок'),
    sa.Column('media', core.database.StrippedString(length=256), nullable=True, comment='СМИ-публикатор (normalized_item.media_name)'),
    sa.Column('region', core.database.StrippedString(length=128), nullable=True, comment='Регион (region.name_display)'),
    sa.Column('macro_region', core.database.StrippedString(length=64), nullable=True, comment='Федеральный округ (region.macro_region)'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Широта центра региона (WGS-84) — метка на карте рынка'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Долгота центра региона (WGS-84) — метка на карте рынка'),
    sa.Column('competitor', core.database.StrippedString(length=256), nullable=True, comment='Конкурент / объект (competitor.name)'),
    sa.Column('source_url', core.database.StrippedString(length=512), nullable=True, comment='Ссылка на событие (normalized_item.url)'),
    sa.Column('priority', core.database.StrippedString(length=8), nullable=False, comment='Приоритет П1..П4'),
    sa.Column('category', core.database.StrippedString(length=128), nullable=False, comment='Категория (category.name)'),
    sa.Column('tonality', core.database.StrippedString(length=32), nullable=False, comment='Тональность'),
    sa.Column('media_index', sa.Numeric(precision=10, scale=2), nullable=True, comment='Медиаиндекс'),
    sa.Column('action', core.database.StrippedString(length=512), nullable=True, comment='Требуемое действие'),
    sa.Column('deadline', sa.Date(), nullable=True, comment='Срок реакции'),
    sa.Column('department', core.database.StrippedString(length=128), nullable=True, comment='Ответственный отдел (department.name)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Комментарий'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Инкрементальный UPSERT, без полной перезагрузки'),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True, comment='Когда BP-5 последний раз проверял строку на значимость — НЕЗАВИСИМО от результата (даже если алерт не сработал). Отбор BP-5: alerted_at IS NULL OR updated_at > alerted_at. Не по журналу alert — там легитимны события с нулём алертов, и по нему нельзя было бы отличить «ещё не проверено» от «проверено, но не значимо»'),
    sa.CheckConstraint('action = btrim(action)', name='ck_showcase_event_action_trimmed'),
    sa.CheckConstraint('category = btrim(category)', name='ck_showcase_event_category_trimmed'),
    sa.CheckConstraint('competitor = btrim(competitor)', name='ck_showcase_event_competitor_trimmed'),
    sa.CheckConstraint('department = btrim(department)', name='ck_showcase_event_department_trimmed'),
    sa.CheckConstraint('macro_region = btrim(macro_region)', name='ck_showcase_event_macro_region_trimmed'),
    sa.CheckConstraint('media = btrim(media)', name='ck_showcase_event_media_trimmed'),
    sa.CheckConstraint('priority = btrim(priority)', name='ck_showcase_event_priority_trimmed'),
    sa.CheckConstraint('region = btrim(region)', name='ck_showcase_event_region_trimmed'),
    sa.CheckConstraint('source_url = btrim(source_url)', name='ck_showcase_event_source_url_trimmed'),
    sa.CheckConstraint('title = btrim(title)', name='ck_showcase_event_title_trimmed'),
    sa.CheckConstraint('tonality = btrim(tonality)', name='ck_showcase_event_tonality_trimmed'),
    sa.ForeignKeyConstraint(['categorized_event_id'], ['categorized_event.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categorized_event_id')
    )
    op.create_index(op.f('ix_showcase_event_category'), 'showcase_event', ['category'], unique=False)
    op.create_index(op.f('ix_showcase_event_competitor'), 'showcase_event', ['competitor'], unique=False)
    op.create_index(op.f('ix_showcase_event_priority'), 'showcase_event', ['priority'], unique=False)
    op.create_index(op.f('ix_showcase_event_published_at'), 'showcase_event', ['published_at'], unique=False)
    op.create_table('action_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showcase_event_id', sa.Integer(), nullable=False, comment='По какому событию витрины заведена задача'),
    sa.Column('task', core.database.StrippedString(length=512), nullable=False, comment='Задача: что конкретно сделать (решение человека)'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='Ответственный отдел'),
    sa.Column('deadline', sa.Date(), nullable=True, comment='Срок'),
    sa.Column('expected_result', sa.Text(), nullable=True, comment='Ожидаемый результат'),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', name='action_status'), server_default=sa.text("'open'"), nullable=False, comment='Статус: open → in_progress → done. Меняют отделы'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда задача заведена'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновляется при смене статуса'),
    sa.CheckConstraint('task = btrim(task)', name='ck_action_item_task_trimmed'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['showcase_event_id'], ['showcase_event.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showcase_event_id', sa.Integer(), nullable=False, comment='По какому событию витрины сработал алерт'),
    sa.Column('event_type_id', sa.Integer(), nullable=False, comment='Какой тип значимого события распознан'),
    sa.Column('priority', sa.Enum('p1', 'p2', 'p3', 'p4', name='priority_level'), nullable=False, comment='Приоритет события на момент алерта (снимок)'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Кому ушло'),
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='Каким каналом'),
    sa.Column('mode', sa.Enum('instant', 'digest', name='delivery_mode'), nullable=False, comment='Снимок режима из правила: instant | digest. По нему джоба-сводка находит свои алерты'),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='alert_status'), server_default=sa.text("'queued'"), nullable=False, comment='queued → sent / failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Текст ошибки при status=failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда завели алерт'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='Когда фактически доставлено'),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['showcase_event_id'], ['showcase_event.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('showcase_event_id', 'channel_id', 'user_id', name='uq_alert_event_channel_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    op.drop_table('action_item')
    op.drop_index(op.f('ix_showcase_event_published_at'), table_name='showcase_event')
    op.drop_index(op.f('ix_showcase_event_priority'), table_name='showcase_event')
    op.drop_index(op.f('ix_showcase_event_competitor'), table_name='showcase_event')
    op.drop_index(op.f('ix_showcase_event_category'), table_name='showcase_event')
    op.drop_table('showcase_event')
    op.drop_index(op.f('ix_categorized_event_categorized_at'), table_name='categorized_event')
    op.drop_table('categorized_event')
    op.drop_table('normalized_item')
    op.drop_table('routing_rule')
    op.drop_table('raw_item')
    op.drop_table('user')
    op.drop_table('source_candidate')
    op.drop_index('uq_search_task_no_trigger', table_name='search_task', postgresql_where=sa.text('trigger_id IS NULL'))
    op.drop_table('search_task')
    op.drop_table('trigger')
    op.drop_table('topic_limit')
    op.drop_table('stop_word')
    op.drop_table('source')
    op.drop_index('ix_region_name_aliases', table_name='region', postgresql_using='gin')
    op.drop_table('region')
    op.drop_index('ix_event_type_keywords', table_name='event_type', postgresql_using='gin')
    op.drop_table('event_type')
    op.drop_table('department')
    op.drop_table('competitor')
    op.drop_table('channel')
    op.drop_table('category')
    op.drop_table('black_domain')
    # ### end Alembic commands ###
