"""bp5_user_recipients_and_alerted_at

Revision ID: 2e3b04e84809
Revises: 505632e81de0
Create Date: 2026-07-28 21:07:03.053341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e3b04e84809'
down_revision: Union[str, Sequence[str], None] = '505632e81de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=True, comment='ФИО — для читаемости в админке, не критично'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='В каком отделе числится (справочно, не для маршрутизации)'),
    sa.Column('email', sa.String(length=256), nullable=False, comment='Адрес для канала email'),
    sa.Column('telegram_login', sa.String(length=64), nullable=False, comment='Логин для канала telegram (без @)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_login')
    )
    op.add_column('alert', sa.Column('user_id', sa.Integer(), nullable=False, comment='Кому ушло'))
    op.drop_constraint(op.f('uq_alert_event_channel'), 'alert', type_='unique')
    op.create_unique_constraint('uq_alert_event_channel_user', 'alert', ['showcase_event_id', 'channel_id', 'user_id'])
    op.drop_constraint(op.f('alert_department_id_fkey'), 'alert', type_='foreignkey')
    op.create_foreign_key(None, 'alert', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('alert', 'department_id')
    op.alter_column('event_type', 'keywords',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               comment='Слова-маркеры: [«прокуратура», «суд», «иск», «нарушения»]. По ним детектор матчит title события (вхождение подстроки)',
               existing_comment='Слова-маркеры через запятую: «прокуратура, суд, иск, нарушения». По ним детектор матчит title события',
               existing_nullable=False,
               # TEXT -> ARRAY не приводится неявно. Разбираем существующий
               # CSV на элементы, срезая пробелы вокруг запятых (формат был
               # 'прокуратура, суд, иск' — с пробелом после запятой).
               postgresql_using=r"regexp_split_to_array(keywords, '\s*,\s*')")
    op.create_index('ix_event_type_keywords', 'event_type', ['keywords'], unique=False, postgresql_using='gin')
    op.add_column('routing_rule', sa.Column('user_id', sa.Integer(), nullable=False, comment='Кому конкретно отправлять'))
    op.drop_constraint(op.f('uq_routing_rule_type_priority_channel'), 'routing_rule', type_='unique')
    op.create_unique_constraint('uq_routing_rule_type_priority_channel_user', 'routing_rule', ['event_type_id', 'priority', 'channel_id', 'user_id'])
    op.drop_constraint(op.f('routing_rule_department_id_fkey'), 'routing_rule', type_='foreignkey')
    op.create_foreign_key(None, 'routing_rule', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('routing_rule', 'department_id')
    op.add_column('showcase_event', sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True, comment='Когда BP-5 последний раз проверял строку на значимость — НЕЗАВИСИМО от результата (даже если алерт не сработал). Отбор BP-5: alerted_at IS NULL OR updated_at > alerted_at. Не по журналу alert — там легитимны события с нулём алертов, и по нему нельзя было бы отличить «ещё не проверено» от «проверено, но не значимо»'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showcase_event', 'alerted_at')
    op.add_column('routing_rule', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='На какой отдел маршрутизируем'))
    op.drop_constraint(None, 'routing_rule', type_='foreignkey')
    op.create_foreign_key(op.f('routing_rule_department_id_fkey'), 'routing_rule', 'department', ['department_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_routing_rule_type_priority_channel_user', 'routing_rule', type_='unique')
    op.create_unique_constraint(op.f('uq_routing_rule_type_priority_channel'), 'routing_rule', ['event_type_id', 'priority', 'channel_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('routing_rule', 'user_id')
    op.drop_index('ix_event_type_keywords', table_name='event_type', postgresql_using='gin')
    op.alter_column('event_type', 'keywords',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               comment='Слова-маркеры через запятую: «прокуратура, суд, иск, нарушения». По ним детектор матчит title события',
               existing_comment='Слова-маркеры: [«прокуратура», «суд», «иск», «нарушения»]. По ним детектор матчит title события (вхождение подстроки)',
               existing_nullable=False,
               postgresql_using="array_to_string(keywords, ', ')")
    op.add_column('alert', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Кому ушло (отдел)'))
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.create_foreign_key(op.f('alert_department_id_fkey'), 'alert', 'department', ['department_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_alert_event_channel_user', 'alert', type_='unique')
    op.create_unique_constraint(op.f('uq_alert_event_channel'), 'alert', ['showcase_event_id', 'channel_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('alert', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
