"""init1

Revision ID: 3db5098075bd
Revises: d34e5dc3a23b
Create Date: 2026-08-08 12:10:19.451015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db5098075bd'
down_revision: Union[str, Sequence[str], None] = 'd34e5dc3a23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_candidate', 'domain',
               existing_type=sa.VARCHAR(length=256),
               nullable=True,
               existing_comment='Найденный домен-кандидат. UNIQUE — не предлагать дважды')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_candidate', 'domain',
               existing_type=sa.VARCHAR(length=256),
               nullable=False,
               existing_comment='Найденный домен-кандидат. UNIQUE — не предлагать дважды')
    # ### end Alembic commands ###
