"""category_department_notes

Revision ID: 505632e81de0
Revises: e9933e09fb13
Create Date: 2026-07-28 16:00:29.430856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '505632e81de0'
down_revision: Union[str, Sequence[str], None] = 'e9933e09fb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorized_event', 'categorized_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда разметили (INSERT) или переразметили (UPDATE). По индексу BP-4 отбирает переразмеченные события (categorized_at > showcase_event.updated_at). onupdate срабатывает автоматически на ЛЮБОМ UPDATE через SQLAlchemy (и точечная правка атрибута, и bulk update()) — колонка не перечислена в .values(), компилятор сам подставит значение. НЕ сработает при INSERT ... ON CONFLICT DO UPDATE (это технически INSERT, не UPDATE) и при правке в обход SQLAlchemy — сырой SQL, DBeaver, pgAdmin: там колонку нужно проставлять руками',
               existing_comment='Когда разметили. По индексу BP-4 отбирает переразмеченные события (categorized_at > showcase_event.updated_at)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('category', sa.Column('note', sa.String(length=512), nullable=True, comment='Определение категории для аналитика: что под неё подпадает'))
    op.add_column('department', sa.Column('note', sa.String(length=512), nullable=True, comment='Зона ответственности отдела: какие категории он ведёт'))
    op.alter_column('department', 'name',
               existing_type=sa.VARCHAR(length=128),
               comment='Отдел: PR, Юристы, Аналитика, Маркетинг',
               existing_comment='Отдел: PR, Тендеры, Юристы, Аналитика, Маркетинг',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'name',
               existing_type=sa.VARCHAR(length=128),
               comment='Отдел: PR, Тендеры, Юристы, Аналитика, Маркетинг',
               existing_comment='Отдел: PR, Юристы, Аналитика, Маркетинг',
               existing_nullable=False)
    op.drop_column('department', 'note')
    op.drop_column('category', 'note')
    op.alter_column('categorized_event', 'categorized_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда разметили. По индексу BP-4 отбирает переразмеченные события (categorized_at > showcase_event.updated_at)',
               existing_comment='Когда разметили (INSERT) или переразметили (UPDATE). По индексу BP-4 отбирает переразмеченные события (categorized_at > showcase_event.updated_at). onupdate срабатывает автоматически на ЛЮБОМ UPDATE через SQLAlchemy (и точечная правка атрибута, и bulk update()) — колонка не перечислена в .values(), компилятор сам подставит значение. НЕ сработает при INSERT ... ON CONFLICT DO UPDATE (это технически INSERT, не UPDATE) и при правке в обход SQLAlchemy — сырой SQL, DBeaver, pgAdmin: там колонку нужно проставлять руками',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
