"""init2

Revision ID: 52e13722df84
Revises: 3db5098075bd
Create Date: 2026-08-08 12:51:19.025036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e13722df84'
down_revision: Union[str, Sequence[str], None] = '3db5098075bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('source_candidate_domain_key'), 'source_candidate', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('source_candidate_domain_key'), 'source_candidate', ['domain'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
