"""bp4_showcase_bi_indexes

Revision ID: 5d726335a128
Revises: 12e96157869f
Create Date: 2026-07-28 13:32:19.676188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d726335a128'
down_revision: Union[str, Sequence[str], None] = '12e96157869f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorized_event', 'categorized_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда разметили. По индексу BP-4 отбирает переразмеченные события (categorized_at > showcase_event.updated_at)',
               existing_comment='Когда разметили',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_categorized_event_categorized_at'), 'categorized_event', ['categorized_at'], unique=False)
    op.create_index(op.f('ix_showcase_event_category'), 'showcase_event', ['category'], unique=False)
    op.create_index(op.f('ix_showcase_event_competitor'), 'showcase_event', ['competitor'], unique=False)
    op.create_index(op.f('ix_showcase_event_priority'), 'showcase_event', ['priority'], unique=False)
    op.create_index(op.f('ix_showcase_event_published_at'), 'showcase_event', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_showcase_event_published_at'), table_name='showcase_event')
    op.drop_index(op.f('ix_showcase_event_priority'), table_name='showcase_event')
    op.drop_index(op.f('ix_showcase_event_competitor'), table_name='showcase_event')
    op.drop_index(op.f('ix_showcase_event_category'), table_name='showcase_event')
    op.drop_index(op.f('ix_categorized_event_categorized_at'), table_name='categorized_event')
    op.alter_column('categorized_event', 'categorized_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда разметили',
               existing_comment='Когда разметили. По индексу BP-4 отбирает переразмеченные события (categorized_at > showcase_event.updated_at)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
