"""add password_reset_code

Revision ID: 5fffb0619842
Revises: 12c9d64c423c
Create Date: 2026-08-04 13:38:41.092357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core.database  # noqa: F401 — для типа StrippedString


# revision identifiers, used by Alembic.
revision: str = '5fffb0619842'
down_revision: Union[str, Sequence[str], None] = '12c9d64c423c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Кому принадлежит код'),
    sa.Column('code_hash', core.database.StrippedString(length=256), nullable=False, comment='bcrypt-хэш 6-значного кода'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Когда код перестаёт быть валиден'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Когда код использован (успешно или исчерпаны попытки)'),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Число неверных попыток ввода — защита от перебора'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда код сгенерирован'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_code')
    # ### end Alembic commands ###
