"""add bp2 models with region aliases

Revision ID: 7097161f6d7f
Revises: b9b37c891d5b
Create Date: 2026-07-25 18:18:12.419329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7097161f6d7f'
down_revision: Union[str, Sequence[str], None] = 'b9b37c891d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _make_aliases(name: str) -> list[str]:
    """Генерирует стандартные псевдонимы из канонического имени города.

    Все варианты — в нижнем регистре, чтобы lookup делался через
    lower(:raw_value) = ANY(name_aliases).
    """
    n = name.lower()
    return list(dict.fromkeys([n, f'г. {n}', f'г {n}']))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=False, comment='Домен публикатора новости (напр. kompromat.ru). НЕ source — то, откуда пришёл контент'),
    sa.Column('reason', sa.String(length=512), nullable=True, comment='Почему в списке: заказной / компрометирующий ресурс'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время добавления домена в чёрный список'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_display', sa.String(length=128), nullable=False, comment='Каноническое имя для витрины и карты: «Волгоград». По нему группируем в дашборде'),
    sa.Column('name_aliases', postgresql.ARRAY(sa.String()), nullable=True, comment='Варианты написания в нижнем регистре: [«волгоград», «г. волгоград», «г волгоград»]'),
    sa.Column('macro_region', sa.String(length=64), nullable=True, comment='Федеральный округ: ЦФО, ЮФО — для карты рынка'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Широта центра региона (WGS-84), для отображения на карте рынка'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Долгота центра региона (WGS-84), для отображения на карте рынка'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_display')
    )
    op.create_index('ix_region_name_aliases', 'region', ['name_aliases'], unique=False, postgresql_using='gin')
    op.create_table('stop_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=512), nullable=False, comment='Слово или фраза для отсева (проверяется вхождением в title/text)'),
    sa.Column('type', sa.Enum('stop_word', 'stop_topic', 'false_positive', name='stop_type'), nullable=False, comment='stop_word — стоп-слово; stop_topic — стоп-тема; false_positive — ложное срабатывание'),
    sa.Column('note', sa.String(length=512), nullable=True, comment='Пояснение для аналитика: почему добавили и от чего защищает'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phrase', 'type', name='uq_stop_word_phrase_type')
    )
    op.create_table('topic_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('competitor', 'source', 'media', 'region', name='limit_scope'), nullable=False, comment='По какой группе считаем долю: competitor / source / media / region'),
    sa.Column('max_count', sa.Integer(), nullable=False, comment='Максимум событий на одну группу за окно; сверх — rejected(noise_limit)'),
    sa.Column('window', sa.Enum('run', 'day', 'week', name='limit_window'), server_default=sa.text("'week'"), nullable=False, comment='Окно подсчёта: run — один прогон, day — сутки, week — неделя'),
    sa.Column('note', sa.String(length=512), nullable=True, comment='Напр.: «СКС занимает ~40% отчёта 5 недель подряд»'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=False, comment='Ссылка назад на сырьё (drill-down, требование прозрачности ТЗ)'),
    sa.Column('competitor_id', sa.Integer(), nullable=True, comment='Конкурент. NULL если из текста однозначно не вытащили'),
    sa.Column('region_id', sa.Integer(), nullable=True, comment='Регион после lookup в region. NULL если не определён'),
    sa.Column('source_id', sa.Integer(), nullable=True, comment='Источник. Денормализовано из raw_item→search_task→source, чтобы не джойнить в два прыжка'),
    sa.Column('published_at', sa.Date(), nullable=True, comment='Дата события, нормализована к ISO из сырой строки (напр. «18 июля 2026»)'),
    sa.Column('title', sa.String(length=512), nullable=False, comment='Заголовок события'),
    sa.Column('media_name', sa.String(length=256), nullable=True, comment='СМИ-публикатор: «Big-news.ru, Москва». NULL для источников без публикатора (напр. hh.ru)'),
    sa.Column('media_domain', sa.String(length=256), nullable=True, comment='Домен публикатора — для сверки с black_domain'),
    sa.Column('url', sa.String(length=512), nullable=True, comment='Ссылка на конкретное событие (НЕ запрос парсера)'),
    sa.Column('text', sa.Text(), nullable=True, comment='Тело события. Вход для стоп-слов в BP-2 и для промпта LLM в BP-3'),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Источник-специфичные факты: {salary_from, salary_to, currency} для вакансий'),
    sa.Column('dedup_key', sa.String(length=64), nullable=False, comment='Хэш бизнес-полей (конкурент|заголовок|дата|регион). UNIQUE = дедуп через ON CONFLICT'),
    sa.Column('status', sa.Enum('ok', 'rejected', name='norm_status'), server_default=sa.text("'ok'"), nullable=False, comment='ok → идут в BP-3; rejected → помечены, не удаляем'),
    sa.Column('reject_reason', sa.Enum('black_domain', 'stop_word', 'stop_topic', 'false_positive', 'noise_limit', 'parse_error', name='reject_reason_t'), nullable=True, comment='Причина отсева. NULL для status=ok'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время нормализации события'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_item.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    # ### end Alembic commands ###

    # --- Сидинг: загружаем города из cities.json ---
    import json
    from pathlib import Path

    cities_file = Path(__file__).parents[2] / 'src' / 'bp2' / 'files' / 'cities.json'
    with open(cities_file, encoding='utf-8') as f:
        cities = json.load(f)

    region_table = sa.table(
        'region',
        sa.column('name_display', sa.String),
        sa.column('name_aliases', postgresql.ARRAY(sa.String)),
        sa.column('macro_region', sa.String),
        sa.column('latitude', sa.Float),
        sa.column('longitude', sa.Float),
    )

    # Дедупликация: в JSON встречаются города-однофамильцы из разных субъектов.
    # Для lookup по имени достаточно одной записи — берём первое вхождение.
    seen: set[str] = set()
    rows = []
    for city in cities:
        name = city['name']
        if name in seen:
            continue
        seen.add(name)
        coords = city.get('coords') or {}
        lat = coords.get('lat')
        lon = coords.get('lon')
        json_aliases: list[str] = city.get('aliases', [])
        merged = list(dict.fromkeys(json_aliases + _make_aliases(name)))
        rows.append({
            'name_display': name,
            'name_aliases': merged,
            'macro_region': city.get('district'),
            'latitude': float(lat) if lat else None,
            'longitude': float(lon) if lon else None,
        })

    op.bulk_insert(region_table, rows)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normalized_item')
    op.drop_table('topic_limit')
    op.drop_table('stop_word')
    op.drop_index('ix_region_name_aliases', table_name='region', postgresql_using='gin')
    op.drop_table('region')
    op.drop_table('black_domain')
    # Удаляем enum-типы PostgreSQL, которые не дропаются вместе с таблицами
    sa.Enum(name='norm_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='reject_reason_t').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='stop_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='limit_scope').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='limit_window').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
