"""init

Revision ID: b9b37c891d5b
Revises:
Create Date: 2026-07-24 19:23:15.129152

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b9b37c891d5b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'competitor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'name',
            sa.String(length=256),
            nullable=False,
            comment='Название компании (например, Бегемот, Рога и Копыта)',
        ),
        sa.Column(
            'inn',
            sa.String(length=12),
            nullable=True,
            comment='ИНН конкурента (опционально, поиск по гос-реестрам)',
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
            comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('inn'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'source',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'name',
            sa.String(length=256),
            nullable=False,
            comment='Имя сайта/ресурса (например, hh.ru, авито, суд_реестр)',
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
            comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'trigger',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'keyword',
            sa.String(length=128),
            nullable=False,
            comment='Само поисковое слово/навык (например, Юрист, Python, Django, Суд)',
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
            comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('keyword'),
    )
    op.create_table(
        'search_task',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'competitor_id',
            sa.Integer(),
            nullable=False,
            comment='Какого конкурента ищем',
        ),
        sa.Column(
            'source_id',
            sa.Integer(),
            nullable=False,
            comment='На каком источнике ищем',
        ),
        sa.Column(
            'trigger_id',
            sa.Integer(),
            nullable=True,
            comment='По какому слову ищем (опционально, NULL = парсим источник в лоб)',
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
            comment='Мягкое выключение записи: не участвует в выборках, из БД не удаляем',
        ),
        sa.ForeignKeyConstraint(
            ['competitor_id'], ['competitor.id'], ondelete='RESTRICT'
        ),
        sa.ForeignKeyConstraint(
            ['source_id'], ['source.id'], ondelete='RESTRICT'
        ),
        sa.ForeignKeyConstraint(
            ['trigger_id'], ['trigger.id'], ondelete='RESTRICT'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'competitor_id',
            'source_id',
            'trigger_id',
            name='uq_search_task_config',
        ),
    )
    op.create_index(
        'uq_search_task_no_trigger',
        'search_task',
        ['competitor_id', 'source_id'],
        unique=True,
        postgresql_where=sa.text('trigger_id IS NULL'),
    )
    op.create_table(
        'raw_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'search_task_id',
            sa.Integer(),
            nullable=False,
            comment='Ссылка на задачу конфигурации. Через неё вытягиваем конкурента, источник и триггер',
        ),
        sa.Column(
            'status',
            sa.Enum('new', 'changed', 'error', name='raw_item_status'),
            server_default=sa.text("'new'"),
            nullable=False,
            comment='new/changed = новая строка; error = сбой сбора. При совпадении хэша строку не создаём, статус не трогаем',
        ),
        sa.Column(
            'content_hash',
            sa.String(length=64),
            nullable=True,
            comment='Хэш от JSON контента для сверки через Redis. NULL при status=error',
        ),
        sa.Column(
            'raw_data',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='Сырой извлечённый контент страницы в формате JSON. NULL при status=error',
        ),
        sa.Column(
            'html_file_path',
            sa.String(length=512),
            nullable=True,
            comment='Путь к сохранённому слепку HTML на диске/S3 для истории. NULL при status=error',
        ),
        sa.Column(
            'source_request_url',
            sa.String(length=512),
            nullable=True,
            comment='Ссылка на оригинальный веб-запрос парсера. NULL при ранней ошибке',
        ),
        sa.Column(
            'error_message',
            sa.Text(),
            nullable=True,
            comment='Текст ошибки при status=error. NULL для успешных',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
            comment='Время первой фиксации этого снимка в системе',
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
            comment='Время последней СВЕРКИ. При совпадении хэша обновляем ТОЛЬКО это поле (статус не трогаем)',
        ),
        sa.ForeignKeyConstraint(
            ['search_task_id'], ['search_task.id'], ondelete='RESTRICT'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_item')
    op.drop_index(
        'uq_search_task_no_trigger',
        table_name='search_task',
        postgresql_where=sa.text('trigger_id IS NULL'),
    )
    op.drop_table('search_task')
    op.drop_table('trigger')
    op.drop_table('source')
    op.drop_table('competitor')
    # ### end Alembic commands ###

    # PG-enum не дропается автоматически при drop_table — убираем вручную,
    # иначе повторный upgrade упадёт на «тип raw_item_status уже существует»
    op.execute('DROP TYPE raw_item_status')
