"""add categorized_event.task

Revision ID: bd1b0f1714a5
Revises: e83ec7313eb4
Create Date: 2026-08-07 12:49:05.787049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd1b0f1714a5'
down_revision: Union[str, Sequence[str], None] = 'e83ec7313eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorized_event', sa.Column('task', postgresql.ARRAY(sa.String()), nullable=True, comment='Список конкретных задач от LLM (GenerationTaskModule): 1-3 практических шага по реализации action'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorized_event', 'task')
    # ### end Alembic commands ###
