"""add action_item.assigned_user_id

Revision ID: d158e734c7bc
Revises: 5fffb0619842
Create Date: 2026-08-04 17:41:27.070685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd158e734c7bc'
down_revision: Union[str, Sequence[str], None] = '5fffb0619842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_item', sa.Column('assigned_user_id', sa.Integer(), nullable=True, comment='Кому конкретно назначена задача (адресат алерта BP-5, если задачу завёл AI-ассистент). NULL — задача отдела в целом, без привязки к конкретному человеку'))
    op.create_foreign_key(None, 'action_item', 'user', ['assigned_user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action_item', type_='foreignkey')
    op.drop_column('action_item', 'assigned_user_id')
    # ### end Alembic commands ###
