"""showcase_coordinates_for_map

Revision ID: e9933e09fb13
Revises: 5d726335a128
Create Date: 2026-07-28 14:57:36.547888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9933e09fb13'
down_revision: Union[str, Sequence[str], None] = '5d726335a128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showcase_event', sa.Column('latitude', sa.Float(), nullable=True, comment='Широта центра региона (WGS-84) — метка на карте рынка'))
    op.add_column('showcase_event', sa.Column('longitude', sa.Float(), nullable=True, comment='Долгота центра региона (WGS-84) — метка на карте рынка'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showcase_event', 'longitude')
    op.drop_column('showcase_event', 'latitude')
    # ### end Alembic commands ###
